// Generated by https://quicktype.io

export interface Product {
  id:         number;
  title:      string;
  slug:       string;
  category:   Category;
  price:      string;
  stock:      number;
  sold:       number;
  image:      string;
  thumbnail:  string;
  created_at: string;
  updated_at: string;
}

export interface Category {
  id:         number;
  name:       string;
  slug:       string;
  created_at: string;
  updated_at: string;
}
