# Generated by Django 3.2.7 on 2022-12-30 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('added_at',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
