# Generated by Django 3.2.7 on 2023-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/default_image.jpeg', null=True, upload_to='user/'),
        ),
    ]
