# Generated by Django 3.2.7 on 2022-12-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('created_at',), 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
