# Generated by Django 3.2.7 on 2022-12-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
