# Generated by Django 3.2.7 on 2023-01-01 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
        migrations.AddField(
            model_name='comment',
            name='star_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
